export interface WeatherSourceProvenance {
  readonly sourceType: "epw" | "synthetic";
  readonly sourceName: string;
  /** Stable public URL or catalog identifier; never a user-specific local path. */
  readonly sourceReference?: string;
  /** ISO calendar date. Deliberately not generated by the parser. */
  readonly retrievedOn?: string;
  /** SHA-256 of the source bytes when supplied by an adapter. */
  readonly sourceSha256?: string;
  readonly notes?: readonly string[];
}

export interface WeatherParseOptions {
  readonly sourceName: string;
  readonly sourceType?: WeatherSourceProvenance["sourceType"];
  readonly sourceReference?: string;
  readonly retrievedOn?: string;
  readonly sourceSha256?: string;
  readonly datasetId?: string;
}
